### ISSUE TITLE
Please make it compatible with Discord Bridge.

### ISSUE THREAD

**Issue by ProsperCraft** [pie-flavor/Boop#1]
https://github.com/nguyenquyhy/DiscordBridge/issues/54#issuecomment-287642021

**Comment by pie-flavor** [comment]
Still not something I can fix. DiscordBridge needs to make a way for custom channels to be utilized. If the proposed fix on their end involves modification on my end, then I'll do that.

**Comment by axle2005** [comment]
@ProsperCraft Whats a good way to test this issue? (Setup, Needs multiple players, etc)

**Comment by pie-flavor** [comment]
@axle2005 You appear to misunderstand. As explained in the linked issue, DiscordBridge filters out any MessageChannel which isn't Sponge's chat channel. Boop uses a custom channel to filter it per-player, which then gets filtered out.

**Comment by axle2005** [comment]
I understood that xD But using the description of Boop, it sounds like I need two people to even test this to begin with :P Someone standing there, and someone talking to then. 

Edit: Okay, after testing I get it... after adding Boop, the default MessageChannel isn't used anymore, thus preventing messages going to discord... got yah.

**Comment by axle2005** [comment]
I just made a commit that will allow support for boop. I dont know if the Author is every actually coming back, but have started doing releases on my fork. Ill probably post a new release including this in a few days.

**Comment by axle2005** [comment]
Guess I forgot to come back... but the latest release on ore supports Boop. 

[2.5.1](https://ore.spongepowered.org/axle2005/Discord-Bridge/versions/2.5.1)
