### ISSUE TITLE
Saw an error in console - ArrayIndexOutOfBoundsException -1

### ISSUE THREAD

**Issue by Blayyke** [pie-flavor/Boop#4]
Running boop 1.6.0 on SpongeForge.
Sponge version:

[20:31:39] [Server thread/INFO] [nucleus]: Server ran the command: /sponge version
[20:31:39] [Server thread/INFO]: SpongeForge
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-SNAPSHOT-06016f2
    SpongeForge: 1.12.2-2611-7.1.0-BETA-2990
    Minecraft Forge: 14.23.2.2611

https://gist.githubusercontent.com/Blayyke/fb5b321d08d73d3a185ca021a87d0471/raw/c635d389c7913e91a830522a6ca3fae48accdd6a/boop%2520error.md

**Comment by pie-flavor** [comment]
I can see what's going wrong. Doesn't need a new version though, nothing is actually prevented from working AFAICT.
